#!/bin/bash

### Check if the dotfiles exist || git clone it

FOLDER=
ROOT=dotfiles
LOG_FILE="$HOME/$ROOT/bash/.bashrc-log"
OS_TYPE=$(uname -a)

[[ ! -d "$HOME/dotfiles" ]] && {
	echo -e "	"
	! git clone https://github.com/IIIMaroIII/dotfiles "$HOME/dotfiles" && {
		echo -e "	Something went wrong, dotfiles repo hasn't been downloaded. Check 'git --version'. Exiting ..."
		exit 1
	}
	echo -e "	Repo successfully downloaded..."
}

declare -A dot_os_files;

find-files(){
	echo "	Starting finding files at $1"
	while IFS= read -r path;do
		basename "$path"	
	done < <(find "$HOME/$ROOT"/"$1" -type f -iname ".bash*" || {
		echo "	Can't find any files in $1. Skipping..."
		return
	})
}

get-files(){
if (( $# != 0 )); then
		echo -e "	Executing time at $(uname -a) on $(date '+%Y-%m-%d %H:%M:%S')" >> $LOG_FILE 

	for os in "$@"; do

		echo -e "	Here's files for: $HOME/$ROOT/$os" >> $LOG_FILE 
		dot_os_files[$os]=$(find-files "$os")
		echo -e "	Files in associative array for $os key: " >> $LOG_FILE
		echo -e "${dot_os_files[$os]}" >> $LOG_FILE 

	done
fi

}

get-files macos linux wsl

set -x

source-files(){
	path="$HOME/$ROOT/$1"
	[[ ! -e "$path" ]] && {
		echo -e "	Folder $1 doesn't exist at $HOME/$ROOT. Skipping ..."
		return
	}
	[[ ! -f "$HOME/$ROOT/bash/.bashrc" ]] && {
		echo -e "	$HOME/$ROOT/bash/.bashrc file doesn't exist. Skipping..."
		return
		}
	}
printf "dot_os_files: %s\n" "${dot_os_files[linux]}"
set +x

### Define the OS_TYPE and symlink appropriate files
#case ${OS_TYPE,,} in 
#	*wsl*) 
#		echo "	You're running on Windows with WSL with $(uname -a)"
#		source-files wsl;;
#		
#	*darwin* ) 
#		echo "	You're running on macOS with $(uname -a)"
#		source-files macos;;
#	*) 
#		echo "	You're running on Linux with $(uname -a)"
#		source-files linux;;
#esac
#
### Source ~/dotfiles/bash/.bashr

ln -sf "$HOME/$ROOT/bash/.bashrc" "$HOME/.bashrc"

# =============== Custom set up ===============


